// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCrudWebApi.Data;

#nullable disable

namespace SimpleCrudWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241210141159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SimpleCrudWebApi.Models.Student", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adi@gmail.com",
                            Name = "Adi"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1982, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "budi@gmail.com",
                            Name = "Budi"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1983, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cyntia@gmail.com",
                            Name = "Cyntia"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1990, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "danang@gmail.com",
                            Name = "Danang"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
